### ISSUE TITLE
sip: Unable to find file "QtCore/QtCoremod.sip"

### ISSUE THREAD

**Issue by marcbone** [ros-noetic-arch/ros-noetic-rviz#1] opened 2020-05-25 07:58 UTC
Building rviz fails for me with this error:
```
[ 57%] Building CXX object src/test/CMakeFiles/line_edit_with_button_test.dir/line_edit_with_button_test.cpp.o
sip: Unable to find file "QtCore/QtCoremod.sip"
[ 58%] Building CXX object src/test/CMakeFiles/line_edit_with_button_test.dir/line_edit_with_button_test_autogen/mocs_compilation.cpp.o
Traceback (most recent call last):
  File "/opt/ros/noetic/share/python_qt_binding/cmake/sip_configure.py", line 110, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '/home/marco/.cache/yay/ros-noetic-rviz/src/build/sip/rviz_sip', '-b', '/home/marco/.cache/yay/ros-noetic-rviz/src/build/sip/rviz_sip/pyqtscripting.sbf', '-I', '/usr/share/sip/PyQt5', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_14_0', '-t', 'WS_X11', 'rviz.sip']' returned non-zero exit status 1.

```

**Comment by acxz** [comment] 2020-05-25 12:03
So I was able to compile `1.13.7-3` just fine yesterday. But now when I tried upgrading to the latest version: `1.14.0` https://github.com/ros-visualization/rviz/releases I am getting another error. See: #2

**Comment by acxz** [comment] 2020-05-25 12:09
As for this specific issue since I cannot reproduce, it will be hard for me to help you debug it.

[ros-noetic-rviz-1.13.7-3-x86_64.pkg.tar.xz.zip](https://github.com/ros-noetic-arch/ros-noetic-rviz/files/4677107/ros-noetic-rviz-1.13.7-3-x86_64.pkg.tar.xz.zip)

If you want you can install the `13.7.0-3` rviz directly from the pkg file uploaded here. Github wouldn't allow me to upload a *.xz file so I had to rename it to a *.zip. Just rename the file with the `.zip` and install it like so: `yay -Syu ros-noetic-rviz-1.13.7-3-x86_64.pkg.tar.xz`

Sorry this is as much as I can help for now, until I get some more time to investigate this. This may even be an upstream issue. Looking at rviz issues on their github or filing one yourself might also be fruitful.

**Comment by marcbone** [comment] 2020-05-26 10:31
I was not able to install the package with yay. But I could install it via the manjaro package installer (pamac).

However, when I was building the rest of noetic I got a similar error in the ros-noetic-qt-gui-cpp package. But I dont want you to invest more time on this as long as I am the only one with this issue. Actually the only reason I wanted to try out noetic is that rqt_reconfigure was crashing in melodic after selecting a config. However, I managed to fix it by copying the python files from github master into my installation. And now it works..
![image](https://user-images.githubusercontent.com/16033059/82889767-8a4eb900-9f4b-11ea-819f-1807d309faf9.png)
... on white backgrounds :rofl: 

So I guess I wont need noetic any time soon. But thanks for keeping up the work :+1:

**Comment by acxz** [comment] 2020-05-26 11:50
Ah Manjaro, hmm it could be something manjaro related. I would recommend using an Arch based distro that uses the same packages as Arch (like [EndeavourOS](https://endeavouros.com/)), since we do not support Manjaro.

thx for reporting the issue tho, i'll keep it open for now until I get rviz compiling properly.
Glad to see you got your stuff to work tho.

**Comment by acxz** [comment] 2020-05-28 22:26
Yeah I was not able to reproduce this issue. Closing.

**Closed as completed by acxz** 2020-05-28 22:26 UTC

**Comment by ATLANTer** [comment] 2022-01-04 23:02
I got similar error
![image](https://user-images.githubusercontent.com/72944305/148135721-fb73c0d3-6483-463f-b084-b9d8166499b8.png)
